

Hyperparams:
  - llm model:
    - name:
    - temperature
  - embedding:
    - name
    - top_k
  - text_splitting:
    - name
    - chunk_size:
    - chunk_overlap:
  - reranker:
    - model_name
    - top_n
  - indexing